import React, { useState } from 'react'
import ProExpCard from './proExpCard';

const ProExp = () => {
    const [sixExpand, setSixExpand] = useState(false);
    const [sevenExpand, setSevenExpand] = useState(false);
    const [eightExpand, setEightExpand] = useState(false);
    const [nineExpand, setNineExpand] = useState(false);

    const handleExpand = (expand, setExpand) => {
        setExpand(!expand)
    }

    return (
        <div className='m-auto relative text-center mt-6 bg-gray-500 rounded-3xl p-2 w-10/12' id='proExpo'>
            <h3><i class="fas fa-user-tie"></i> Professional Experience <i class="fas fa-user-tie"></i></h3>
            <div>
                <ProExpCard
                    cardHeaderTitle={'Ford Motor Company | Aug 2021 - Present | Full Stack Developer'}
                    cardHeaderSubHeader={'KOTLIN | JAVA | REACT'}
                    image={require('../../Images/Ford.jpg')}
                    imageTitle={'Ford'}
                    cardContentBody={" I Have been working as a software engineer at Ford Credit since August of 2021 on mainly two products, Non-Vehicle Asset Financing and the Commercial Line of Credit Application. Both products were started since my joining of the team and have received multiple accolades and both products continue to be expanded further. Our team practices Extreme Programming and TDD."}
                    expand={sixExpand}
                    handleExpand={() => handleExpand(sixExpand, setSixExpand)}
                    site={"https://Ford.com"}
                    siteDisplay={"Ford.com"}
                />
                <ProExpCard
                    cardHeaderTitle={'Hygieia | Jan 2021 | Full Stack Developer'}
                    cardHeaderSubHeader={'NODE | REACT'}
                    image={require('../../Images/Hygieia.PNG')}
                    imageTitle={'Hygieia'}
                    cardContentBody={" Contracted to consult with Hygieia to develop and deploy a web form for a patient to assign their benefits to Hygieia. Integrate the new AOB form with existing intake user flow currently deployed. Modify a NODE web service to persist the data gathered by physicians in a PDF as well as a MSSQL database deployed on Hygieia's AWS container. Manage and deploy source code from a GitHub account owned by Hygieia, Inc. and deploy website to Hygieia’s web servers."}
                    expand={sevenExpand}
                    handleExpand={() => handleExpand(sevenExpand, setSevenExpand)}
                    site={"https://hygieia.com/"}
                    siteDisplay={"hygieia.com"}
                />
                <ProExpCard
                    cardHeaderTitle={'Bridges To Prosperity | Oct 2020 | Full Stack Developer'}
                    cardHeaderSubHeader={'NODE | JEST | REACT | ANT DESIGN | MATERIAL UI | MAPBOX | PLOTLY'}
                    image={require('../../Images/BTP.PNG')}
                    imageTitle={'Bridges To Prosperity'}
                    cardContentBody={"Worked on a cross-functional team of 4 data scientists and 4 web developers over 4 weeks to display data generated by the Data Science team on a map for the stakeholder to better be able to evaluate new and existing bridge site locations. Added topography and different icons to the map functionality. Integrated new output from our data scientist’s model into our backend API service. Updated the styling of the app to match the current web site. With my personal updates of adding topography and adding graphs with PlotlyJs our version of the project was chosen to continue to build on by the stakeholder."}
                    expand={eightExpand}
                    handleExpand={() => handleExpand(eightExpand, setEightExpand)}
                    site={"https://www.bridgestoprosperity.org/"}
                    siteDisplay={"bridgestoprosperity.org"}
                    gitHub={"https://github.com/meloegel/bridges-to-prosperity-be-a/tree/readme-loegel"}
                    gitHubDisplay={"github.com/meloegel/bridges-to-prosperity-be-a/tree/readme-loegel"}
                />
                <ProExpCard
                    cardHeaderTitle={'Ultramikro | Nov 2020 | Front End Developer'}
                    cardHeaderSubHeader={'REACT | MATERIAL UI'}
                    image={require('../../Images/Ultramikro.PNG')}
                    imageTitle={'Ultramikro'}
                    cardContentBody={"Contracted to recover what was possible from previous site and create and deploy new site Originally created the project in HTML in approximately 3 days. Deployed May 2020 Re-created the site in React in Oct in approximately 3 days. Deployed Oct 2020 Stakeholder happy with new site, remain in contact for future updates of the site."}
                    expand={nineExpand}
                    handleExpand={() => handleExpand(nineExpand, setNineExpand)}
                    site={"https://ultramikro.vercel.app/"}
                    siteDisplay={"ultramikro.vercel.app"}
                    gitHub={"https://github.com/meloegel/ultraMikro"}
                    gitHubDisplay={"github.com/meloegel/ultraMikro"}
                />
            </div>
        </div>
    )
}

export default ProExp;

