import React, { useState } from 'react'
import clsx from 'clsx';
import { makeStyles } from '@material-ui/core/styles';
import Card from '@material-ui/core/Card';
import CardHeader from '@material-ui/core/CardHeader';
import CardMedia from '@material-ui/core/CardMedia';
import CardContent from '@material-ui/core/CardContent';
import Typography from '@material-ui/core/Typography';
import IconButton from '@material-ui/core/IconButton';
import ExpandMoreIcon from '@material-ui/icons/ExpandMore';
import CardActions from '@material-ui/core/CardActions';
import Collapse from '@material-ui/core/Collapse';
import Tooltip from '@material-ui/core/Tooltip';

const useStyles = makeStyles((theme) => ({
    media: {
        height: 0,
        paddingTop: '56.25%',
        border: '1px solid black',
    },
    expand: {
        transform: 'rotate(0deg)',
        marginLeft: 'auto',
        transition: theme.transitions.create('transform', {
            duration: theme.transitions.duration.shortest,
        }),
    },
    expandOpen: {
        transform: 'rotate(180deg)',
    }
}));

const ProExp = () => {
    const classes = useStyles();
    const [sixExpand, setSixExpand] = useState(false);
    const handleSixExpand = () => {
        setSixExpand(!sixExpand)
    }
    return (
        <div className='proExpDiv'>
            <h3>Professional Experience</h3>
            <div>
                <div className='projectCardSection'>
                    <Card
                        style={{ backgroundColor: '#a6acba' }}
                        className='proExpCard'
                        raised
                    >
                        <CardHeader
                            style={{ color: 'white', textShadow: '.5px .5px black' }}
                            title='Bridges To Prosperity'
                            subheader='Oct 2020'
                        />
                        <div className='proExpContentDivSwitch'>
                            <div className='proExpContent'>
                                <a href='https://github.com/meloegel/bridges-to-prosperity-fe-a'>
                                    <CardMedia
                                        className={classes.media}
                                        image={require('../styles/Images/BTP.PNG')}
                                        title='Bridges To Prosperity'
                                    />
                                </a>
                            </div>
                            <div className='proExpContent'>
                                <CardContent>
                                    <Typography variant="body1" style={{ color: 'white', minHeight: '235px' }}>
                                        Worked on a cross-functional team of 4 data scientists and 4 web developers over 4 weeks to display data generated by the Data Science team on a map for the stakeholder to better be able to evaluate new and existing bridge site locations. Added topography and different icons to the map functionality. Integrated new output from our data scientist’s model into our backend API service. Updated the styling of the app to match the current web site. With my personal updates of adding topography and adding graphs with PlotlyJs our version of the project was chosen to continue to build on by the stakeholder.
                                </Typography>
                                </CardContent>
                            </div>
                        </div>
                        <CardActions>
                            <Tooltip
                                placement='left'
                                title='Links'
                            >
                                <IconButton
                                    className={clsx(classes.expand, {
                                        [classes.expandOpen]: sixExpand,
                                    })}
                                    onClick={handleSixExpand}
                                    aria-expanded={sixExpand}
                                    aria-label="links"
                                ><ExpandMoreIcon /></IconButton>
                            </Tooltip>
                        </CardActions>
                        <Collapse in={sixExpand} timeout="auto" unmountOnExit>
                            <CardContent>
                                <Typography variant="body1" style={{ color: 'white' }}>GitHub FE: <a className='cardLink' href='https://github.com/meloegel/bridges-to-prosperity-fe-a'>github.com/meloegel/bridges-to-prosperity-fe-a</a></Typography>
                                <Typography variant="body1" style={{ color: 'white' }}>GitHub BE: <a className='cardLink' href='https://github.com/meloegel/bridges-to-prosperity-be-a'>github.com/meloegel/bridges-to-prosperity-be-a</a></Typography>
                            </CardContent>
                        </Collapse>
                    </Card>
                </div>
                <div className='projectCardSection'>
                    <Card
                        style={{ backgroundColor: '#a6acba' }}
                        className='proExpCard'
                        raised
                    >
                        <CardHeader
                            style={{ color: 'white', textShadow: '.5px .5px black' }}
                            title='Ultramikro'
                            subheader='Nov 2020'
                        />
                        <div className='proExpContentDiv'>
                            <div className='proExpContent'>
                                <a href='https://github.com/meloegel/ultraMikro'>
                                    <CardMedia
                                        className={classes.media}
                                        image={require('../styles/Images/Ultramikro.PNG')}
                                        title='Ultramikro'
                                    />
                                </a>
                            </div>
                            <div className='proExpContent'>
                                <CardContent>
                                    <Typography variant="body1" style={{ color: 'white', minHeight: '235px' }}>
                                        Contracted to recover what was possible from previous site and create and deploy new site
                                        Originally created the project in HTML in approximately 3 days. Deployed May 2020
                                        Re-created the site in React in Oct in approximately 3 days. Deployed Oct 2020
                                        Stakeholder happy with new site, remain in contact for future updates of the site
                                </Typography>
                                </CardContent>
                            </div>
                        </div>
                        <CardActions>
                            <Tooltip
                                placement='left'
                                title='Links'
                            >
                                <IconButton
                                    className={clsx(classes.expand, {
                                        [classes.expandOpen]: sixExpand,
                                    })}
                                    onClick={handleSixExpand}
                                    aria-expanded={sixExpand}
                                    aria-label="links"
                                ><ExpandMoreIcon /></IconButton>
                            </Tooltip>
                        </CardActions>
                        <Collapse in={sixExpand} timeout="auto" unmountOnExit>
                            <CardContent>
                                <Typography variant="body1" style={{ color: 'white' }}>GitHub: <a className='cardLink' href='https://github.com/meloegel/ultraMikro'>github.com/meloegel/ultraMikro</a></Typography>
                            </CardContent>
                        </Collapse>
                    </Card>
                </div>
            </div>
        </div>
    )
}

export default ProExp;

